name: Install via Nix and Test
on:
  pull_request:
  push:
jobs:

  build-and-test:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        py: [38]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - uses: cachix/cachix-action@v8
        with:
          name: jacg-next-exp
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_JACG_NEXT_EXP }}'
      - name: Install dependencies via Nix
        run: nix-shell --argstr py ${{ matrix.py }}
      - name: Build Nexus with SCons
        run: nix-shell --argstr py ${{ matrix.py }} --run "scons"
      - name: Run bin/nexus-test
        run: nix-shell --argstr py ${{ matrix.py }} --run "bin/nexus-test"
      - name: Run pytests
        run: nix-shell --argstr py ${{ matrix.py }} --run "pytest -x"
